spring:
  application:
    name: studentInfo
  datasource:
    studentInfo:
      url: jdbc:mysql://172.172.178.75:3306/t
      username: root
      password: Root@123
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 600000
      type: org.apache.tomcat.jdbc.pool.DataSource

mybatis:
  typeAliasesPackage: org.zzr1000.springTest.model
  mapperLocations: classpath:/mapper/StudentMapper.xml